'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const { joinCanonicalCostsWithOperationalRows, operationalCargoDigest }=require('../electron/cargo-table-projection');
const { cargoFleetAccountFromCycleId }=require('../electron/influx-data');
const cost=(overrides={})=>({isoDate:'2026-08-05',faction:'MUD',instance:'MUD',fleetAccount:'fleet-a',fleet:'fleet-a',allocationKey:'fleet:fleet-a',allocationStatus:'scoped',sourceMode:'canonical_raw',burnedFuelExact:'12.5',burnedFuel:12.5,txFeeLamports:'5001',txCostSolExact:'0.000005001',txCostSol:0.000005001,txsDaily:3,fuelValuation:{status:'provisional',amountATLExact:'1.25',amountATL:1.25,eventDay:'2026-08-05',priceDay:'2026-08-04'},solValuation:{status:'incomplete',amountATL:null,amountATLExact:null,eventDay:'2026-08-05',priceDay:null,reason:'provisional_seed_missing'},sourceIds:['a','b'],...overrides});
const op=(overrides={})=>({isoDate:'2026-08-05',faction:'MUD',instance:'MUD',fleetAccount:'fleet-a',fleet:'CF-05|01',assignment:'Transport',txsDaily:116,completedCycleIds:['c1','c2'],cargoCycles:2,cargoLegs:4,starbases:['MRZ-5'],travelTimeByMode:{warp:100,subwarp:0},travelModeTime:{warpPercent:100,subwarpPercent:0,label:'100% Warp | 0% Subwarp'},...overrides});

test('authoritative fleet account is extracted from the immutable cycle identity',()=>{assert.equal(cargoFleetAccountFromCycleId('2jLH4L71cSTRRBzCLpshhsfPTJAmVaYHmNZ1AK3wZsBp:2,-23:1785886870821'),'2jLH4L71cSTRRBzCLpshhsfPTJAmVaYHmNZ1AK3wZsBp');assert.equal(cargoFleetAccountFromCycleId('CF-05|01'),null);});

test('matching canonical cost and operational row produce one identity-safe complete projection',()=>{const [r]=joinCanonicalCostsWithOperationalRows({costRows:[cost()],operationalRows:[op()]});assert.equal(r.fleet,'CF-05|01');assert.equal(r.fleetAccount,'fleet-a');assert.equal(r.assignment,'Transport');assert.equal(r.txsDaily,3);assert.equal(r.cargoCycles,2);assert.equal(r.cargoLegs,4);assert.deepEqual(r.starbases,['MRZ-5']);assert.equal(r.burnedFuelExact,'12.5');assert.equal(r.operationalStatus,'joined');assert.equal(r.solValuation.status,'incomplete');});
test('identity includes UTC day, faction, instance, and fleet account',()=>{const rows=joinCanonicalCostsWithOperationalRows({costRows:[cost()],operationalRows:[op({isoDate:'2026-08-04'}),op({faction:'ONI'}),op({instance:'OTHER'}),op({fleetAccount:'fleet-b'}),op()]});assert.equal(rows.length,1);assert.equal(rows[0].txsDaily,3);});
test('multiple operational fragments deterministically become one fleet/day row without double-counting costs',()=>{const a=op({txsDaily:2,completedCycleIds:['c1'],cargoCycles:1,cargoLegs:2,travelTimeByMode:{warp:20,subwarp:0}});const b=op({txsDaily:3,completedCycleIds:['c2'],cargoCycles:1,cargoLegs:2,travelTimeByMode:{warp:30,subwarp:0}});const forward=joinCanonicalCostsWithOperationalRows({costRows:[cost()],operationalRows:[a,b]});const reverse=joinCanonicalCostsWithOperationalRows({costRows:[cost()],operationalRows:[b,a]});assert.equal(forward.length,1);assert.equal(forward[0].txsDaily,3);assert.equal(forward[0].cargoCycles,2);assert.equal(forward[0].burnedFuelExact,'12.5');assert.deepEqual(forward,reverse);assert.equal(operationalCargoDigest(forward),operationalCargoDigest(reverse));});
test('cost-only and unallocated rows fail closed instead of inventing operational values',()=>{const rows=joinCanonicalCostsWithOperationalRows({costRows:[cost(),cost({fleetAccount:'',fleet:null,allocationKey:'unallocated:v1:MUD:MUD:2026-08-05:sol_fee',allocationStatus:'unallocated',eventType:'sol_fee',burnedFuelExact:'0',burnedFuel:0})],operationalRows:[]});for(const r of rows){assert.equal(r.operationalStatus,'incomplete');assert.equal(r.txsDaily,3);assert.equal(r.cargoCycles,null);assert.equal(r.assignment,null);assert.equal(r.travelModeTime,null);assert.deepEqual(r.starbases,[]);}assert.equal(rows[1].allocationStatus,'unallocated');});
test('legacy rows are passed through unchanged and strict cutover cannot duplicate them',()=>{const legacy={isoDate:'2026-08-04',fleet:'CF-05|01',txsDaily:202,cargoCycles:51};const result=joinCanonicalCostsWithOperationalRows({legacyRows:[legacy],costRows:[cost()],operationalRows:[op(),op({isoDate:'2026-08-04'})]});assert.equal(result.length,2);assert.strictEqual(result[0],legacy);assert.equal(result.filter(r=>r.isoDate==='2026-08-04').length,1);});
test('missing volume or capacity remains null while genuine zero is retained',()=>{const [missing]=joinCanonicalCostsWithOperationalRows({costRows:[cost()],operationalRows:[op({cargoVolume:null,fleetCargoCapacity:null})]});assert.equal(missing.cargoVolume,null);assert.equal(missing.fleetCargoCapacity,null);const [zero]=joinCanonicalCostsWithOperationalRows({costRows:[cost()],operationalRows:[op({cargoVolume:0,fleetCargoCapacity:100})]});assert.equal(zero.cargoVolume,0);assert.equal(zero.fleetCargoCapacity,100);});
test('incomplete SOL display remains explanatory null rather than zero or zero percent',()=>{const renderer=fs.readFileSync(path.join(__dirname,'..','electron','renderer.js'),'utf8');assert.match(renderer,/incomplete-valuation-indicator/);assert.match(renderer,/Incomplete valuation · event day/);assert.match(renderer,/txsCostsPct'\) return valuationCell\(entry\.txsCostsPercent/);assert.doesNotMatch(renderer,/txsCostsPercent \|\| 0/);assert.match(renderer,/cargoEfficiencyPercent == null \? '--'/);assert.match(renderer,/rentalRateAtlasPerDay == null \? '--'/);});
test('join/projection adds no RPC, timer, polling, pricing, or refresh behavior',()=>{const source=fs.readFileSync(path.join(__dirname,'..','electron','cargo-table-projection.js'),'utf8');assert.doesNotMatch(source,/Connection\(|getAccountInfo|fetch\(|setInterval|setTimeout|poll|refresh|priceATL/i);});
