'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const fixture=require('./fixtures/cargo-cf22-completed-cycle.json');
const {buildCargoAllocationRecords}=require('../electron/influx-data');
const {buildCostLedgerResult}=require('../electron/production-ledger-events');
const {buildCargoBetaInputs,buildCargoBreakevenBetaRows}=require('../electron/cargo-breakeven-beta');
const main=fs.readFileSync(require.resolve('../electron/main'),'utf8'),renderer=fs.readFileSync(require.resolve('../electron/renderer'),'utf8'),html=fs.readFileSync(require.resolve('../electron/renderer.html'),'utf8');
function evidence(){const allocations=buildCargoAllocationRecords(fixture.allocationRows,new Set(['2026-07-25']));const cargoRows=[{isoDate:'2026-07-25',fleetAccount:allocations[0].fleetAccount,assignment:'Supply Chain',fleetName:'CF-22|01b',profile:'USTUR',faction:'USTUR',burnedFuel:17835.494841372823,fuelCostsAtlas:178.35494841372823,rentalRateAtlasPerDay:12,txCostSol:0.000003750409485994295,txsCostsAtlas:0.0003750409485994295}];return{allocations,cargoRows}}

test('production Break-even replaces cargoRows empty literal with completed scoped allocations',()=>{assert.doesNotMatch(main,/cargoRows:\s*\[\],\s*\n\s*craftingRows/);assert.match(main,/cargoRows: ledgerCargoRows/);assert.match(main,/scopedCargoAllocationRows/);assert.match(main,/completedCargoCycleIds\.has/);assert.match(main,/buildCargoAllocationRecordsFromPivotRows/)});
test('provenance-bound CF-22 completed cycle produces one populated Cargo beta input',()=>{const {allocations,cargoRows}=evidence(),rows=buildCargoBetaInputs({allocations,cargoRows});assert.equal(rows.length,1);assert.equal(rows[0].cycleId,fixture.completionRows[0].cycleId);assert.equal(rows[0].asset,'Field Stabilizer');assert.equal(rows[0].deliveredQuantity,15648);assert.ok(rows[0].fuelCost>0);assert.equal(rows[0].rentalCost,12);assert.ok(rows[0].transactionCost>0);assert.ok(rows[0].ledgerRow)});
test('before empty Cargo input versus after completed allocation changes projection',()=>{const {allocations,cargoRows}=evidence();assert.equal(buildCargoBetaInputs({allocations:[],cargoRows}).length,0);assert.equal(buildCargoBetaInputs({allocations,cargoRows}).length,1)});
test('Cargo C/U remains visible when opening Base history is incomplete',()=>{const {allocations,cargoRows}=evidence(),inputs=buildCargoBetaInputs({allocations,cargoRows});const ledger=buildCostLedgerResult({openingInventoryRows:[{timestamp:'2026-07-24T00:00:00Z',starbase:'MRZ-21',asset:'Field Stabilizer',quantity:20000}],cargoRows:inputs.map(x=>x.ledgerRow)});const rows=buildCargoBreakevenBetaRows({betaInputs:inputs,appliedEventResults:ledger.appliedEventResults});assert.ok(rows[0].cargoCostPerUnit>0);assert.equal(rows[0].baseCostPerUnit,null);assert.equal(rows[0].totalCostPerUnit,null);assert.match(rows[0].evidenceStatus,/Incomplete — Base basis incomplete/)});
test('representable legacy Base and Cargo evidence produces estimated totals',()=>{const {allocations,cargoRows}=evidence(),inputs=buildCargoBetaInputs({allocations,cargoRows});const ledger=buildCostLedgerResult({miningRows:[{isoDate:'2026-07-24',starbase:'MRZ-21',rawMaterial:'Field Stabilizer',mined:20000,totalCostsAtlas:100}],cargoRows:inputs.map(x=>x.ledgerRow)});const row=buildCargoBreakevenBetaRows({betaInputs:inputs,appliedEventResults:ledger.appliedEventResults})[0];assert.ok(row.baseCostPerUnit>0);assert.ok(row.cargoCostPerUnit>0);assert.equal(row.totalCostPerUnit,row.baseCostPerUnit+row.cargoCostPerUnit);assert.equal(row.evidenceStatus,'Estimated — legacy evidence')});
test('checkpoint replay retains transfer basis for the visible Beta',()=>{const {allocations,cargoRows}=evidence(),inputs=buildCargoBetaInputs({allocations,cargoRows}),first=buildCostLedgerResult({miningRows:[{isoDate:'2026-07-24',starbase:'MRZ-21',rawMaterial:'Field Stabilizer',mined:20000,totalCostsAtlas:100}],cargoRows:inputs.map(x=>x.ledgerRow)}),second=buildCostLedgerResult({initialLedger:first.ledger,eventFingerprintCounts:first.eventFingerprintCounts,eventResultsByFingerprint:first.eventResultsByFingerprint,cargoRows:inputs.map(x=>x.ledgerRow)});const row=buildCargoBreakevenBetaRows({betaInputs:inputs,appliedEventResults:second.appliedEventResults})[0];assert.equal(second.skippedDuplicateEvents.length,1);assert.ok(row.baseCostPerUnit>0);assert.ok(row.cargoCostPerUnit>0)});
test('missing Rental cost is specific and never rendered as zero',()=>{const {allocations,cargoRows}=evidence();delete cargoRows[0].rentalRateAtlasPerDay;const input=buildCargoBetaInputs({allocations,cargoRows})[0],row=buildCargoBreakevenBetaRows({betaInputs:[input],appliedEventResults:[]})[0];assert.equal(row.rentalCost,null);assert.equal(row.cargoCostPerUnit,null);assert.match(row.evidenceStatus,/Incomplete — Rental cost missing/);assert.doesNotMatch(row.evidenceStatus,/Rental cost missing.*0/)});
test('visible Beta table and renderer expose all required columns',()=>{for(const label of ['Break-even Beta · Completed Cargo cycles','Delivered Asset','Delivered Quantity','Fuel Cost','Rental Cost','Transaction Cost','Cargo C/U','Base C/U','Total C/U','Evidence / Status'])assert.match(html,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(renderer,/function renderCargoBreakevenBeta/);assert.match(renderer,/entry\.evidenceStatus/)});
test('renderer DOM proof shows values and incomplete reason without zero substitution',()=>{const match=renderer.match(/function renderCargoBreakevenBeta\(result\) \{[\s\S]*?\n\}/);assert.ok(match);const body={children:[],textContent:'',appendChild(node){this.children.push(node)}};const context={earningsCargoBreakevenBetaBody:body,earningsCargoBreakevenBetaStatus:{},setText:(node,text)=>node.text=text,formatWholeNumber:String,formatAtlasNumber:(v)=>String(v),createTextCell:(text)=>({textContent:String(text),colSpan:1}),document:{createElement:()=>({children:[],appendChild(node){this.children.push(node)}})}};vm.runInNewContext(`${match[0]};renderCargoBreakevenBeta({cargoBreakevenBetaRows:[{isoDate:'2026-07-25',origin:'MRZ-21',destination:'MRZ-22',asset:'Field Stabilizer',deliveredQuantity:15648,fuelCost:1,rentalCost:null,transactionCost:0.1,cargoCostPerUnit:null,baseCostPerUnit:null,totalCostPerUnit:null,evidenceStatus:'Incomplete — Rental cost missing'}]})`,context);const cells=body.children[0].children.map(x=>x.textContent);assert.ok(cells.includes('Field Stabilizer'));assert.ok(cells.includes('Incomplete — Rental cost missing'));assert.equal(cells[5],'--')});
test('legacy Cargo and Earnings render paths remain present and unchanged in ownership',()=>{assert.match(renderer,/function renderEarningsCargo\(result\)/);assert.match(renderer,/const rows = Array\.isArray\(result\.cargoRows\)/);assert.match(main,/cargoRows: cargo,/);assert.match(main,/cargoBreakevenBetaRows,/)});
