'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {stableJson,projectCargoDeliveryEvidence,joinCargoDeliveryAllocations}=require('../electron/cargo-delivery-evidence');
const {buildAuthoritativeCargoBetaInputs}=require('../electron/cargo-breakeven-beta');
const {buildAuthoritativeCargoTransferEvents}=require('../electron/production-ledger-events');
const {ExactInventoryCostLedger,COMPLETE}=require('../electron/exact-inventory-cost-ledger');
const PROGRAM='SAGE2HAwep459SNq61LHvjxPk4pLPEJLoMETef7f7EE', SIG='S8Z2n6QsVc1DAHuUaVRAFUkoZbyQzp2T1v3yfY9d7rTkMmibQUSMn7feVAk6PEaNDaT7uwzwaegGiZx8o5CAHAm', FLEET='DDdAJk2KZZtJNVa7J1qdRzMW4tgfvJLrjMhU5Ct12uwy', MINT='11111111111111111111111111111111';
function row(o={}){const r={_time:'2026-08-24T08:43:22.808Z',faction:'UST',fleet:'CF-22|01b',rss:'Field Stabilizer',assignment:'Supply Chain',originStarbase:'MRZ-21',deliveryStarbase:'MRZ-22',cycleId:`${FLEET}:35,16:1`,allocationIndex:'0',amount:'1',cargoVolume:'6',allocatedFuel:'1.25',allocatedTxCostSol:'0.000001',assetMint:MINT,deliveryEvidenceSchemaVersion:'1',deliveryMovementType:'unload',deliverySignature:SIG,deliveryOuterInstructionIndex:'3',deliveryConfirmedSlot:'361234567',deliveryConfirmedBlockTime:'1787561002',deliveryRawAmount:'19999000000',deliveryMintDecimals:'6',deliveryDecimalAmount:'19999',deliveryProgramId:PROGRAM,deliveryFleetAccount:FLEET,deliveryFactionProfile:'UST',deliveryProfileAccount:'profile',deliveryRoute:'MRZ-21→MRZ-22',deliveryAllocationId:'allocation-0',...o};r.deliveryEventId=o.deliveryEventId||`cargo-delivery:v1:${r.deliveryProgramId}:${r.deliverySignature}:${r.deliveryOuterInstructionIndex}:unload`;const p={schemaVersion:1,movementType:r.deliveryMovementType,signature:r.deliverySignature,outerInstructionIndex:Number(r.deliveryOuterInstructionIndex),programId:r.deliveryProgramId,slot:Number(r.deliveryConfirmedSlot),blockTime:Number(r.deliveryConfirmedBlockTime),rawAmount:r.deliveryRawAmount,mintDecimals:Number(r.deliveryMintDecimals),decimalAmount:r.deliveryDecimalAmount,mint:r.assetMint,fleetAccount:r.deliveryFleetAccount,fleetLabel:r.fleet,factionProfile:r.deliveryFactionProfile,profileAccount:r.deliveryProfileAccount,route:r.deliveryRoute,cycleId:r.cycleId,allocationId:r.deliveryAllocationId,eventId:r.deliveryEventId};r.deliveryEvidencePayloadHash=o.deliveryEvidencePayloadHash||crypto.createHash('sha256').update(stableJson(p)).digest('hex');return r}
const costs=[{isoDate:'2026-08-24',fleetAccount:FLEET,assignment:'Supply Chain',fleetName:'CF-22|01b',profile:'profile',faction:'UST',burnedFuel:4,fuelCostsAtlas:8,rentalRateAtlasPerDay:3,txCostSol:0.000003,txsCostsAtlas:6}];

test('v265 amount-one anchor creates one full exact Beta and authoritative transfer',()=>{const p=projectCargoDeliveryEvidence([row()]),j=joinCargoDeliveryAllocations(p),b=buildAuthoritativeCargoBetaInputs({joinedDeliveries:j.joinedDeliveries,cargoRows:costs});assert.equal(b.length,1);assert.equal(b[0].deliveredQuantity,'19999');assert.equal(b[0].rawQuantity,'19999000000');assert.equal(b[0].replayCount,1);assert.equal(b[0].confirmedBlockTime,'1787561002');assert.equal(b[0].confirmedSlot,'361234567');const e=buildAuthoritativeCargoTransferEvents(b.map(x=>x.ledgerRow));assert.equal(e.length,1);assert.equal(e[0].quantity.atoms,'19999000000');assert.equal(e[0].eventId,b[0].deliveryEventId)});
test('v264 split replay retains two allocations, sums costs once, and emits one transfer',()=>{const a=row(),b={...a,allocationIndex:'1',amount:'19998',cargoVolume:'4',allocatedFuel:'2.75',allocatedTxCostSol:'0.000002'},p=projectCargoDeliveryEvidence([a,b]),j=joinCargoDeliveryAllocations(p),inputs=buildAuthoritativeCargoBetaInputs({joinedDeliveries:j.joinedDeliveries,cargoRows:costs});assert.equal(j.allocationRows.length,2);assert.equal(j.joinedDeliveries.length,1);assert.equal(inputs.length,1);assert.equal(inputs[0].replayCount,2);assert.equal(inputs[0].allocatedFuel,4);assert.equal(inputs[0].allocatedTxCostSol,0.000003);assert.equal(buildAuthoritativeCargoTransferEvents(inputs.map(x=>x.ledgerRow)).length,1)});
test('conflict and ambiguous cost joins fail closed',()=>{const a=row(),conflict=row({allocationIndex:'1',deliveryEvidencePayloadHash:'f'.repeat(64)});assert.equal(joinCargoDeliveryAllocations(projectCargoDeliveryEvidence([a,conflict])).joinedDeliveries.length,0);const second=row({deliveryOuterInstructionIndex:'4',deliveryAllocationId:'allocation-1'}),untagged={...a,allocationIndex:'9',deliveryEventId:'',deliveryEvidencePayloadHash:'',deliveryRawAmount:'',deliveryMintDecimals:'',deliveryDecimalAmount:''};const joined=joinCargoDeliveryAllocations(projectCargoDeliveryEvidence([a,second,untagged]));assert.equal(joined.joinedDeliveries.length,0);assert.equal(joined.ambiguous.length,2)});
test('multiple unload indexes stay distinct and limiting is by logical delivery',()=>{const second=row({deliveryOuterInstructionIndex:'4',deliveryAllocationId:'allocation-1',allocationIndex:'1',assetMint:'22222222222222222222222222222222',rss:'Electronics'}),j=joinCargoDeliveryAllocations(projectCargoDeliveryEvidence([second,row()]),{limit:1});assert.equal(j.joinedDeliveries.length,1);assert.equal(j.logicalDeliveryCount,2)});
test('exact ledger applies authoritative transfer once across checkpoint replay without Number quantity',()=>{const p=projectCargoDeliveryEvidence([row()]),b=buildAuthoritativeCargoBetaInputs({joinedDeliveries:joinCargoDeliveryAllocations(p).joinedDeliveries,cargoRows:costs})[0],event=buildAuthoritativeCargoTransferEvents([b.ledgerRow])[0],scope={faction:'UST',profile:'profile'},boundary={checkpointId:'open',boundaryAt:'2026-08-24T00:00:00Z',coverage:COMPLETE},l=new ExactInventoryCostLedger({scope,boundary});l.acquire({eventId:'seed',lotId:'seed',provenance:'opening',scope,timestamp:'2026-08-24T00:00:01Z',location:'MRZ-21',asset:'Field Stabilizer',quantity:{atoms:'39998000000',decimals:6,unit:`asset:${MINT}`},base:{mining:{atoms:'10',decimals:0,unit:'ATLAS'}},cargo:{},currency:'ATLAS',status:COMPLETE,coverage:COMPLETE});const cargoEvent={...event,scope,currency:'ATLAS',addedCargo:{fuel:{atoms:'1',decimals:0,unit:'ATLAS'}}},first=l.applyAuthoritativeCargoTransfer(cargoEvent);assert.equal(first.quantity.atoms,'19999000000');const reloaded=ExactInventoryCostLedger.fromValidatedCheckpoint({schemaVersion:2,faction:'UST',playerProfile:'profile',openingCheckpointId:'open',forwardBoundary:'2026-08-24T00:00:00.000Z',lots:l.snapshot(),appliedEvents:Array.from(l.eventIds,eventId=>({eventId}))});assert.equal(reloaded.applyAuthoritativeCargoTransfer(cargoEvent).status,'replay')});
test('huge tiny and legacy evidence never route through authoritative Number mutation',()=>{const huge=row({deliveryRawAmount:'9'.repeat(80),deliveryMintDecimals:'18',deliveryDecimalAmount:`${'9'.repeat(62)}.${'9'.repeat(18)}`}),tiny=row({deliveryOuterInstructionIndex:'4',deliveryAllocationId:'tiny',assetMint:'22222222222222222222222222222222',deliveryRawAmount:'1',deliveryMintDecimals:'18',deliveryDecimalAmount:'0.000000000000000001'}),legacy={...row(),cycleId:'legacy-cycle',deliveryEventId:'',deliveryEvidencePayloadHash:'',deliveryRawAmount:'',deliveryMintDecimals:'',deliveryDecimalAmount:''};const p=projectCargoDeliveryEvidence([huge,tiny,legacy]),j=joinCargoDeliveryAllocations(p);assert.equal(j.joinedDeliveries[0].rawAmount,'9'.repeat(80));assert.equal(j.joinedDeliveries[1].decimalAmount,'0.000000000000000001');assert.equal(j.legacyAllocations.length,1);assert.equal(buildAuthoritativeCargoTransferEvents([{...legacy,evidenceStatus:'legacy_unverified'}]).length,0)});
