'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const cp=require('../electron/exact-ledger-checkpoint');const {ExactInventoryCostLedger,COMPLETE}=require('../electron/exact-inventory-cost-ledger');
const scope={faction:'USTUR',profile:'profile-complete-key'},boundary={checkpointId:'opening-1',boundaryAt:'2026-07-24T00:00:00.000Z',coverage:COMPLETE};
const h=x=>cp.hash(x),q=(atoms,decimals=0,unit='asset:X')=>({atoms,decimals,unit}),c=(atoms,decimals=0)=>({atoms,decimals,unit:'ATLAS'});
const store=(events=[],extra={})=>({schemaVersion:1,events:events.map(e=>({event:e})),conflicts:[],coverage:[],...extra});
function fixture(root,over={}){const l=new ExactInventoryCostLedger({scope,boundary});l.acquire({eventId:'event-1',lotId:'lot-1',provenance:'immutable:test',scope,timestamp:'2026-08-01T00:00:00.000Z',location:'UST-1',asset:'Carbon',quantity:q('3'),base:{mining:c('1')},cargo:{},currency:'ATLAS',status:COMPLETE,coverage:COMPLETE});const payloadHash=h({payload:1});const eventStore=store([{eventId:'event-1',payloadHash,supersedes:null}]);return{root,faction:scope.faction,playerProfile:scope.profile,openingCheckpointId:'opening-1',openingCheckpointHash:h('opening'),forwardBoundary:boundary.boundaryAt,immutableEventStoreVersion:1,eventStoreContentHash:h('store'),appliedEvents:[{eventId:'event-1',payloadHash}],lots:l.snapshot(),coverage:COMPLETE,eventStore,...over}}
async function tmp(){return fs.mkdtemp(path.join(os.tmpdir(),'exact-cp-'))}

test('path uses complete profile fingerprint and separate v2 name',()=>{const p=cp.pathsFor('/tmp/root','USTUR','profile-complete-key');assert.equal(path.basename(p.document),'exact-ledger-checkpoint-v2.json');assert.equal(path.basename(p.directory),cp.fingerprint('USTUR','profile-complete-key'));assert.equal(path.basename(p.directory).length,64)});
test('first create load and exact lot round trip',async()=>{const root=await tmp(),input=fixture(root);const made=await cp.saveExactLedgerCheckpoint(input,{now:'2026-08-02T00:00:00.000Z'});assert.equal(made.status,'created');const loaded=await cp.loadExactLedgerCheckpoint(input);assert.equal(loaded.status,'loaded');assert.deepEqual(loaded.document.lots,made.document.lots);assert.equal((await fs.stat(cp.pathsFor(root,input.faction,input.playerProfile).document)).mode&0o777,0o600)});
test('no change restart is byte stable without rewrite',async()=>{const root=await tmp(),input=fixture(root),p=cp.pathsFor(root,input.faction,input.playerProfile).document;await cp.saveExactLedgerCheckpoint(input,{now:'2026-08-02T00:00:00.000Z'});const before=await fs.readFile(p);const result=await cp.saveExactLedgerCheckpoint(input,{now:'2026-08-03T00:00:00.000Z'});assert.equal(result.status,'no-change');assert.deepEqual(await fs.readFile(p),before)});
test('legacy v1 is legacy approximate rebuild required',async()=>{const root=await tmp(),input=fixture(root),p=cp.pathsFor(root,input.faction,input.playerProfile);await fs.mkdir(p.directory,{recursive:true});await fs.writeFile(p.document,JSON.stringify({schemaVersion:1}));const r=await cp.loadExactLedgerCheckpoint(input);assert.equal(r.status,'legacy-approximate');assert.equal(r.reason,'rebuild-required')});
test('scope and profile mismatch fail closed',async()=>{const root=await tmp(),input=fixture(root);await cp.saveExactLedgerCheckpoint(input);const source=cp.pathsFor(root,input.faction,input.playerProfile).document,target=cp.pathsFor(root,input.faction,'other');await fs.mkdir(target.directory,{recursive:true});await fs.copyFile(source,target.document);const r=await cp.loadExactLedgerCheckpoint({...input,playerProfile:'other'});assert.equal(r.status,'scope-mismatch')});
test('opening hash and boundary mismatches block reuse',async()=>{const root=await tmp(),input=fixture(root);await cp.saveExactLedgerCheckpoint(input);assert.equal((await cp.loadExactLedgerCheckpoint({...input,openingCheckpointHash:h('changed')})).status,'binding-mismatch');assert.equal((await cp.loadExactLedgerCheckpoint({...input,forwardBoundary:'2026-07-25T00:00:00.000Z'})).status,'binding-mismatch')});
test('tampered quantity component and content hash are invalid',async()=>{for(const mutate of [d=>d.lots[0].quantity.atoms='4',d=>d.lots[0].base.mining.atoms='2',d=>d.contentHash='0'.repeat(64)]){const root=await tmp(),input=fixture(root),p=cp.pathsFor(root,input.faction,input.playerProfile).document;await cp.saveExactLedgerCheckpoint(input);const d=JSON.parse(await fs.readFile(p));mutate(d);await fs.writeFile(p,JSON.stringify(d));assert.equal((await cp.loadExactLedgerCheckpoint(input)).status,'invalid')}});
test('resealed conservation failure is invalid',async()=>{const root=await tmp(),input=fixture(root),p=cp.pathsFor(root,input.faction,input.playerProfile).document;await cp.saveExactLedgerCheckpoint(input);const d=JSON.parse(await fs.readFile(p));d.lots[0].total.atoms='9';d.contentHash=cp.hash(Object.fromEntries(Object.entries(d).filter(([k])=>k!=='contentHash')));await fs.writeFile(p,JSON.stringify(d));assert.equal((await cp.loadExactLedgerCheckpoint(input)).status,'invalid')});
test('compatible appended event requires deterministic advance',async()=>{const root=await tmp(),input=fixture(root);await cp.saveExactLedgerCheckpoint(input);const next={eventId:'event-2',payloadHash:h('two'),supersedes:null};const r=await cp.loadExactLedgerCheckpoint({...input,eventStore:store([...input.eventStore.events.map(x=>x.event),next])});assert.equal(r.status,'advance-required');assert.deepEqual(r.appendedEventIds,['event-2'])});
test('appended conflict retains checkpoint with incomplete readiness',async()=>{const root=await tmp(),input=fixture(root);await cp.saveExactLedgerCheckpoint(input);const r=await cp.loadExactLedgerCheckpoint({...input,eventStore:{...input.eventStore,conflicts:[{conflictKey:h('c')}]}});assert.equal(r.status,'loaded');assert.equal(r.readiness,'Incomplete')});
test('correction superseding applied event requires rebuild',async()=>{const root=await tmp(),input=fixture(root);await cp.saveExactLedgerCheckpoint(input);const correction={eventId:'event-2',payloadHash:h('two'),supersedes:'event-1'};assert.equal((await cp.loadExactLedgerCheckpoint({...input,eventStore:store([...input.eventStore.events.map(x=>x.event),correction])})).status,'rebuild-required')});
test('missing or changed applied event requires rebuild',async()=>{const root=await tmp(),input=fixture(root);await cp.saveExactLedgerCheckpoint(input);assert.equal((await cp.loadExactLedgerCheckpoint({...input,eventStore:store([])})).status,'rebuild-required');assert.equal((await cp.loadExactLedgerCheckpoint({...input,eventStore:store([{eventId:'event-1',payloadHash:h('changed')}])})).status,'rebuild-required')});
test('coverage improvement requires rebuild',async()=>{const root=await tmp(),input=fixture(root,{coverage:'Incomplete'});await cp.saveExactLedgerCheckpoint(input);const improved={...input.eventStore,coverage:[{record:{status:'Complete'}}]};assert.equal((await cp.loadExactLedgerCheckpoint({...input,eventStore:improved})).status,'rebuild-required')});
test('interrupted write preserves previous bytes',async()=>{const root=await tmp(),input=fixture(root),p=cp.pathsFor(root,input.faction,input.playerProfile).document;await cp.saveExactLedgerCheckpoint(input);const before=await fs.readFile(p);const changed={...input,eventStoreContentHash:h('new-store'),coverage:'Incomplete'};const r=await cp.saveExactLedgerCheckpoint(changed,{writeHooks:{beforeRename:()=>{throw new Error('interrupt')}}});assert.equal(r.status,'save-failed');assert.deepEqual(await fs.readFile(p),before)});
test('concurrent writers serialize and leave a valid checkpoint',async()=>{const root=await tmp(),input=fixture(root);const [a,b]=await Promise.all([cp.saveExactLedgerCheckpoint(input),cp.saveExactLedgerCheckpoint(input)]);assert.deepEqual([a.status,b.status].sort(),['created','no-change']);assert.equal((await cp.loadExactLedgerCheckpoint(input)).status,'loaded')});
test('corrupt and unsupported schemas are preserved and block overwrite',async()=>{for(const text of ['{bad',JSON.stringify({schemaVersion:99})]){const root=await tmp(),input=fixture(root),p=cp.pathsFor(root,input.faction,input.playerProfile);await fs.mkdir(p.directory,{recursive:true});await fs.writeFile(p.document,text);assert.equal((await cp.saveExactLedgerCheckpoint(input)).status,'invalid');assert.equal(await fs.readFile(p.document,'utf8'),text)}});
test('restart replay preserves tiny and very large values',async()=>{const root=await tmp(),input=fixture(root);input.lots[0].quantity=q('1',36);input.lots[0].base.mining=c('9'.repeat(128));await cp.saveExactLedgerCheckpoint(input);const first=await cp.loadExactLedgerCheckpoint(input),second=await cp.loadExactLedgerCheckpoint(input);assert.equal(first.document.lots[0].quantity.atoms,'1');assert.equal(first.document.lots[0].base.mining.atoms,'9'.repeat(128));assert.deepEqual(second.document,first.document)});
test('canonical exact validation rejects numeric units and incompatible component currency',async()=>{const root=await tmp(),input=fixture(root);input.lots[0].quantity=3;assert.equal((await cp.saveExactLedgerCheckpoint(input)).status,'save-failed');const other=fixture(await tmp());other.lots[0].base.mining={atoms:'1',decimals:0,unit:'USDC'};assert.equal((await cp.saveExactLedgerCheckpoint(other)).status,'save-failed')});
