'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const shadow=require('../electron/exact-shadow-projection'),cp=require('../electron/exact-ledger-checkpoint');
const arithmetic=require('../electron/exact-arithmetic');
const COMPLETE='Complete',INCOMPLETE='Incomplete',scope={faction:'USTUR',playerProfile:'profile-1'};
const q=(atoms,decimals=0,unit='asset:X')=>({atoms,decimals,unit}),c=(atoms,decimals=0)=>({atoms,decimals,unit:'ATLAS'}),h=x=>cp.hash(x);
function opening(over={}){const value={checkpointId:'opening-1',...scope,boundaryAt:'2026-07-24T00:00:00.000Z',lots:[],...over};value.contentHash=h(shadow.openingContent(value));return value}
function event(id,time='2026-08-01T00:00:00.000Z',over={}){return{eventId:id,payloadHash:h({id,over}),faction:scope.faction,playerProfile:scope.playerProfile,eventTimestamp:time,sourceSystem:'lm',supersedes:null,accounting:{type:'acquire',source:'lm',lotId:`lot-${id}`,location:'UST-1',asset:'Food',quantity:q('1'),base:{lm:c('2')},cargo:{},currency:'ATLAS'},...over}}
function store(events=[],over={}){const value={schemaVersion:1,events:events.map(e=>({event:e,eligibility:e.eligibility||COMPLETE})),conflicts:[],coverage:[],...over};value.contentHash=h(value);return value}
async function input(events=[],over={}){return{root:await fs.mkdtemp(path.join(os.tmpdir(),'shadow-')),...scope,opening:opening(),eventStore:store(events),...over}}

test('deterministic cold replay sorts authoritative time then event ID',async()=>{const a=event('a','2026-08-01T00:00:01.000Z'),b=event('b','2026-08-01T00:00:00.000Z');const i=await input([a,b]);const r=await shadow.coldProject(i,{now:'2026-08-02T00:00:00.000Z'});assert.equal(r.status,'created');assert.deepEqual(r.appliedEventIds,['b','a']);assert.deepEqual(r.checkpoint.appliedEvents.map(x=>x.eventId),['a','b'])});
test('restart with unchanged store is no change and byte stable',async()=>{const i=await input([event('a')]),p=cp.pathsFor(i.root,i.faction,i.playerProfile).document;await shadow.coldProject(i,{now:'2026-08-02T00:00:00.000Z'});const before=await fs.readFile(p);const r=await shadow.projectShadow(i,{now:'2026-08-03T00:00:00.000Z'});assert.equal(r.status,'no-change');assert.equal(r.written,false);assert.deepEqual(await fs.readFile(p),before)});
test('compatible append advances and applies event exactly once',async()=>{const first=event('a'),i=await input([first]);await shadow.coldProject(i);const second=event('b','2026-08-02T00:00:00.000Z');i.eventStore=store([first,second]);const r=await shadow.projectShadow(i);assert.equal(r.status,'saved');assert.deepEqual(r.advancedEventIds,['b']);const again=await shadow.projectShadow(i);assert.equal(again.status,'no-change');assert.equal(again.checkpoint.lots.length,2)});
test('correction affecting applied event triggers rebuild',async()=>{const first=event('a'),i=await input([first]);await shadow.coldProject(i);i.eventStore=store([first,event('b','2026-08-02T00:00:00.000Z',{supersedes:'a'})]);const r=await shadow.projectShadow(i);assert.equal(r.status,'rebuild-required');assert.equal(r.reason,'applied-event-corrected')});
test('coverage improvement triggers rebuild',async()=>{const first=event('a',{},{eligibility:INCOMPLETE});const i=await input([first]);i.eventStore.coverage=[{record:{status:INCOMPLETE}}];i.eventStore.contentHash=h(i.eventStore);await shadow.coldProject(i);i.eventStore={...i.eventStore,coverage:[{record:{status:COMPLETE}}]};i.eventStore.contentHash=h(i.eventStore);assert.equal((await shadow.projectShadow(i)).status,'rebuild-required')});
test('relevant conflict makes projection incomplete',async()=>{const e=event('a'),i=await input([e]);i.eventStore=store([e],{conflicts:[{eventId:'a'}]});const r=await shadow.coldProject(i);assert.equal(r.projectionStatus,INCOMPLETE);assert.equal(r.conflicts.relevant.length,1)});
test('unrelated conflict is review evidence without corrupting projection',async()=>{const e=event('a'),i=await input([e]);i.eventStore=store([e],{conflicts:[{eventId:'unrelated'}]});const r=await shadow.coldProject(i);assert.equal(r.projectionStatus,COMPLETE);assert.equal(r.conflicts.unrelated.length,1)});
test('unsupported and incomplete sources run but stay incomplete without zero costs',async()=>{const scan=event('scan','2026-08-01T00:00:00.000Z',{sourceSystem:'scanning',accounting:{type:'acquire',source:'scanning',lotId:'scan',location:'UST-1',asset:'SDU',quantity:q('1'),base:{},cargo:{},currency:'ATLAS'}}),lm=event('lm','2026-08-02T00:00:00.000Z',{eligibility:INCOMPLETE});const i=await input([scan,lm]);const r=await shadow.coldProject(i);assert.equal(r.projectionStatus,INCOMPLETE);assert.deepEqual(r.unsupportedEventIds,['scan']);assert.equal(r.checkpoint.lots.length,1)});
test('stale opening binding and changed applied event require rebuild',async()=>{const e=event('a'),i=await input([e]);await shadow.coldProject(i);i.opening=opening({checkpointId:'other'});assert.equal((await shadow.projectShadow(i)).status,'binding-mismatch');i.opening=opening();i.eventStore=store([{...e,payloadHash:h('changed')}]);assert.equal((await shadow.projectShadow(i)).status,'rebuild-required')});
test('cross profile and faction events are rejected',async()=>{for(const changed of [{playerProfile:'other'},{faction:'MUD'}]){const i=await input([event('a','2026-08-01T00:00:00.000Z',changed)]);await assert.rejects(()=>shadow.coldProject(i),/scope-mismatch/)}});
test('order-independent event input produces identical lots and applied IDs',async()=>{const a=event('a','2026-08-02T00:00:00.000Z'),b=event('b','2026-08-01T00:00:00.000Z'),one=await input([a,b]),two=await input([b,a]);const x=await shadow.coldProject(one),y=await shadow.coldProject(two);assert.deepEqual(x.appliedEventIds,y.appliedEventIds);assert.deepEqual(x.checkpoint.lots,y.checkpoint.lots)});
test('legacy comparator passes aligned representable values',()=>{const exact=[{scope:{faction:'USTUR',profile:'p'},location:'A',asset:'X',quantity:q('2'),baseTotal:c('2'),cargoTotal:c('0'),total:c('2'),baseCostPerUnit:c('1'),cargoCostPerUnit:c('0'),totalCostPerUnit:c('1'),status:COMPLETE}];const legacy=[{faction:'USTUR',profile:'p',location:'A',asset:'X',quantity:2,baseTotal:2,cargoTotal:0,total:2,baseCostPerUnit:1,cargoCostPerUnit:0,totalCostPerUnit:1,status:COMPLETE}];assert.equal(shadow.compareLegacyExact(exact,legacy)[0].classification,'PASS')});
test('legacy comparator compares exact C/U ratios without importing float state',()=>{const ratio=arithmetic.ratio(c('1'),q('2')).value,row={scope:{faction:'USTUR',profile:'p'},location:'A',asset:'X',quantity:q('2'),baseTotal:c('1'),cargoTotal:c('0'),total:c('1'),baseCostPerUnit:ratio,cargoCostPerUnit:arithmetic.ratio(c('0'),q('2')).value,totalCostPerUnit:ratio,status:COMPLETE};const legacy={faction:'USTUR',profile:'p',location:'A',asset:'X',quantity:2,baseTotal:1,cargoTotal:0,total:1,baseCostPerUnit:.5,cargoCostPerUnit:0,totalCostPerUnit:.5,status:COMPLETE};assert.equal(shadow.compareLegacyExact([row],[legacy])[0].classification,'PASS')});
test('legacy comparator classifies proven exactness and coverage differences',()=>{const row={scope:{faction:'USTUR',profile:'p'},location:'A',asset:'X',quantity:q('1'),baseTotal:c('1'),cargoTotal:c('0'),total:c('1'),baseCostPerUnit:c('1'),cargoCostPerUnit:c('0'),totalCostPerUnit:c('1'),status:INCOMPLETE};const base={faction:'USTUR',profile:'p',location:'A',asset:'X',quantity:1,baseTotal:.3333333333333333,cargoTotal:0,total:.3333333333333333,baseCostPerUnit:.3333333333333333,cargoCostPerUnit:0,totalCostPerUnit:.3333333333333333,status:INCOMPLETE};assert.equal(shadow.compareLegacyExact([row],[{...base,differenceProof:'binary-fraction-vs-atom-allocation'}])[0].classification,'REVIEW — EXPECTED EXACTNESS DIFFERENCE');assert.equal(shadow.compareLegacyExact([row],[{...base,coverageDifference:true}])[0].classification,'REVIEW — COVERAGE DIFFERENCE')});
test('legacy comparator blocks unexplained invariant and nonfinite differences',()=>{const row={scope:{faction:'USTUR',profile:'p'},location:'A',asset:'X',quantity:q('1'),baseTotal:c('1'),cargoTotal:c('0'),total:c('1'),baseCostPerUnit:c('1'),cargoCostPerUnit:c('0'),totalCostPerUnit:c('1'),status:COMPLETE};const legacy={faction:'USTUR',profile:'p',location:'A',asset:'X',quantity:2,baseTotal:1,cargoTotal:0,total:1,baseCostPerUnit:1,cargoCostPerUnit:0,totalCostPerUnit:1,status:COMPLETE};assert.equal(shadow.compareLegacyExact([row],[legacy])[0].classification,'BLOCK — INVARIANT DIFFERENCE');assert.equal(shadow.compareLegacyExact([row],[{...legacy,quantity:Infinity}])[0].classification,'BLOCK — INVARIANT DIFFERENCE')});
test('readiness matrix contains every gate and current source matrix is not ready',()=>{const r=shadow.readinessMatrix({openingSnapshot:false,forwardBoundary:true,identitySupport:'partial',backfillCoverage:false,relevantConflicts:0,correctionsResolved:true,executionCustody:'partial',currencyUnits:true,checkpointCurrent:false,reconciliation:true,deterministicReplay:true,noLegacyMixing:true});assert.equal(r.allGatesPresent,true);assert.equal(Object.keys(r.gates).length,12);assert.equal(r.overall,'NOT READY');assert.deepEqual(r.sourceMatrix,{scanning:'unsupported',mining:'unsupported',crafting:'provisional',cargo:'provisional',upgrading:'provisional',lm:'conditional',gm:'conditional'})});
test('all passing gates are mechanically ready but do not alter current evidence',()=>{const evidence=Object.fromEntries(shadow.GATES.map(g=>[g,true]));evidence.relevantConflicts=0;evidence.noLegacyMixing=true;assert.equal(shadow.readinessMatrix(evidence).overall,'READY')});
