'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { ExactInventoryCostLedger, COMPLETE, INCOMPLETE } = require('../electron/exact-inventory-cost-ledger');
const { renderRatio } = require('../electron/exact-arithmetic');
const scope = { faction: 'USTUR', profile: 'profile-1' };
const boundary = { checkpointId: 'opening-1', boundaryAt: '2026-07-24T00:00:00.000Z', coverage: COMPLETE };
const q = (atoms, decimals = 0, unit = 'asset:unit') => ({ atoms, decimals, unit });
const c = (atoms, decimals = 0, unit = 'ATLAS') => ({ atoms, decimals, unit });
let sequence = 0;
function event(overrides = {}) { sequence += 1; return { eventId: `event-${sequence}`, lotId: `lot-${sequence}`, provenance: 'immutable:test', scope,
  timestamp: `2026-08-01T00:00:${String(sequence % 60).padStart(2, '0')}.000Z`, location: 'UST-1', asset: 'Carbon', quantity: q('1'),
  base: {}, cargo: {}, currency: 'ATLAS', status: COMPLETE, coverage: COMPLETE, ...overrides }; }
function ledger() { return new ExactInventoryCostLedger({ scope, boundary }); }
function atoms(row, path) { return path.split('.').reduce((value, key) => value[key], row).atoms; }
function ratio(row, key) { return renderRatio(row[key]).value; }

test('hard migration boundary rejects legacy numeric state and every numeric exact field', () => {
  assert.deepEqual(ExactInventoryCostLedger.fromLegacySnapshot([{ quantity: 1 }]), { status: INCOMPLETE, reason: 'rebuild-required' });
  assert.throws(() => new ExactInventoryCostLedger({ scope, boundary: { ...boundary, coverage: INCOMPLETE } }), /rebuild-required/);
  assert.throws(() => ledger().acquire(event({ quantity: 1 })), /quantity/);
  assert.throws(() => ledger().acquire(event({ base: { mining: 1 } })), /base.mining/);
});

test('golden 1 scanning acquisition is exact', () => { const l=ledger(); l.acquire(event({asset:'Survey Data Unit',quantity:q('100'),base:{scanning:c('5')}})); const r=l.reconcile('UST-1','Survey Data Unit'); assert.equal(atoms(r,'quantity'),'100'); assert.equal(atoms(r,'base.scanning'),'5'); assert.equal(ratio(r,'totalCostPerUnit'),'0.050000000000000000'); });
test('golden 2 mining shared pool allocations conserve exactly', () => { const l=ledger(); l.acquire(event({quantity:q('60'),base:{mining:c('6')}})); l.acquire(event({asset:'Iron Ore',quantity:q('40'),base:{mining:c('4')}})); assert.equal(BigInt(l.reconcile('UST-1','Carbon').baseTotal.atoms)+BigInt(l.reconcile('UST-1','Iron Ore').baseTotal.atoms),10n); });
test('golden 3 LM purchase fee is represented once', () => { const l=ledger(); l.purchase({execution:{eventId:'lm-1',eligible:true,coverage:COMPLETE,market:'lm',fees:[{id:'fee-1',value:c('3',1),ownerProven:true}],provenance:'lm',scope,timestamp:'2026-08-01T01:00:00Z',currency:'ATLAS'},custodyFlows:[{executionId:'lm-1',proven:true,lotId:'lm-lot',location:'UST-1',asset:'Food',quantity:q('10'),payment:c('12')}]}); assert.equal(l.reconcile('UST-1','Food').base.lm.atoms,'123'); });
test('golden 4 GM purchase remains at wallet until proven transfer', () => { const l=ledger(); l.acquire(event({location:'wallet:gm',asset:'Fuel',quantity:q('20'),base:{gm:c('8')}})); assert.equal(l.reconcile('UST-1','Fuel').reason,'missing-exact-history'); assert.equal(l.reconcile('wallet:gm','Fuel').quantity.atoms,'20'); });
test('golden 5 FIFO whole and split GM movement is deterministic', () => { const l=ledger(); l.acquire(event({location:'wallet:gm',asset:'Fuel',quantity:q('30'),base:{gm:c('12')}})); l.transfer(event({location:'wallet:gm',destination:'MUD-1',asset:'Fuel',quantity:q('10'),currency:'ATLAS',addedCargo:{}})); l.transfer(event({location:'wallet:gm',destination:'UST-1',asset:'Fuel',quantity:q('20'),currency:'ATLAS',addedCargo:{}})); assert.equal(l.reconcile('MUD-1','Fuel').base.gm.atoms,'4'); assert.equal(l.reconcile('UST-1','Fuel').base.gm.atoms,'8'); });
test('golden 6 crafting carries ingredient basis and conversion basis', () => { const l=ledger(); l.acquire(event({quantity:q('10'),base:{mining:c('5')}})); l.craft(event({outputAsset:'Framework',outputQuantity:q('2'),ingredients:[{location:'UST-1',asset:'Carbon',quantity:q('10')}],craftingCost:c('3')})); const r=l.reconcile('UST-1','Framework'); assert.equal(r.base.mining.atoms,'5'); assert.equal(r.base.crafting.atoms,'3'); assert.equal(ratio(r,'totalCostPerUnit'),'4.000000000000000000'); });
test('golden 7 Cargo Fuel Rental and TX are added once', () => { const l=ledger(); l.acquire(event({quantity:q('100'),base:{mining:c('20')}})); l.transfer(event({destination:'UST-2',quantity:q('40'),addedCargo:{fuel:c('2'),rental:c('1'),tx:c('1')},currency:'ATLAS'})); const r=l.reconcile('UST-2','Carbon'); assert.equal(r.base.mining.atoms,'8'); assert.equal(r.cargoTotal.atoms,'4'); assert.equal(ratio(r,'totalCostPerUnit'),'0.300000000000000000'); });
test('golden 8 sale returns exact COGS and retained basis', () => { const l=ledger(); l.acquire(event({asset:'Food',quantity:q('10'),base:{lm:c('20')}})); const out=l.sell(event({asset:'Food',quantity:q('4')})); assert.equal(out.base.lm.atoms,'8'); assert.equal(l.reconcile('UST-1','Food').base.lm.atoms,'12'); });
test('golden 9 opening lot is uncosted Incomplete and remains so after movement', () => { const l=ledger(); l.seedOpening(event({kind:'opening',openingCheckpointId:'opening-1',asset:'Biomass',quantity:q('7')})); assert.equal(l.reconcile('UST-1','Biomass').status,INCOMPLETE); l.transfer(event({asset:'Biomass',quantity:q('3'),destination:'UST-2',currency:'ATLAS',addedCargo:{tx:c('1')}})); assert.equal(l.reconcile('UST-2','Biomass').status,INCOMPLETE); assert.equal(l.reconcile('UST-2','Biomass').totalCostPerUnit,null); });
test('golden 10 split transfer and consumption reconcile quantity and basis', () => { const l=ledger(); l.acquire(event({location:'A',asset:'X',quantity:q('10'),base:{mining:c('5')}})); l.transfer(event({location:'A',destination:'B',asset:'X',quantity:q('4'),currency:'ATLAS',addedCargo:{tx:c('1')}})); const used=l.upgrade(event({location:'B',asset:'X',quantity:q('1')})); assert.equal(BigInt(l.reconcile('A','X').quantity.atoms)+BigInt(l.reconcile('B','X').quantity.atoms)+BigInt(used.quantity.atoms),10n); assert.equal(BigInt(l.reconcile('A','X').base.mining.atoms)+BigInt(l.reconcile('B','X').base.mining.atoms)+BigInt(used.base.mining.atoms),5n); });
test('golden 11 tiny nonzero basis differs from exact zero', () => { const l=ledger(); l.acquire(event({asset:'Tiny',quantity:q('2'),base:{mining:c('2',8)}})); l.acquire(event({asset:'Zero',quantity:q('2'),base:{mining:c('0',8)}})); assert.equal(ratio(l.reconcile('UST-1','Tiny'),'baseCostPerUnit'),'0.000000010000000000'); assert.equal(ratio(l.reconcile('UST-1','Zero'),'baseCostPerUnit'),'0.000000000000000000'); });
test('golden 12 exact replay is stable and creates no second lot', () => { const l=ledger(); const e=event({quantity:q('5'),base:{mining:c('2')}}); const first=l.acquire(e); assert.equal(l.acquire(e).status,'replay'); assert.equal(l.snapshot().length,1); assert.equal(l.snapshot()[0].lotId,first.lotId); });

test('whole and split transfers conserve indivisible residual atoms deterministically', () => { const l=ledger(); l.acquire(event({location:'A',asset:'X',quantity:q('3'),base:{mining:c('1')}})); l.transfer(event({location:'A',destination:'B',asset:'X',quantity:q('1'),currency:'ATLAS',addedCargo:{}})); assert.equal(BigInt(l.reconcile('A','X').baseTotal.atoms)+BigInt(l.reconcile('B','X').baseTotal.atoms),1n); assert.deepEqual(l.snapshot(),l.snapshot()); });
test('multi-flow marketplace purchase never duplicates execution fee', () => { const l=ledger(); l.purchase({execution:{eventId:'gm-many',eligible:true,coverage:COMPLETE,market:'gm',fees:[{id:'fee',value:c('1'),ownerProven:true}],provenance:'gm',scope,timestamp:'2026-08-01T02:00:00Z',currency:'ATLAS'},custodyFlows:[{executionId:'gm-many',proven:true,lotId:'a',location:'A',asset:'X',quantity:q('1'),payment:c('2')},{executionId:'gm-many',proven:true,lotId:'b',location:'B',asset:'X',quantity:q('1'),payment:c('3')}]}); assert.equal(BigInt(l.reconcile('A','X').base.gm.atoms)+BigInt(l.reconcile('B','X').base.gm.atoms),6n); });
test('custody alone cannot create a purchase and unrelated flow fails closed', () => { const l=ledger(); assert.equal(l.purchase({execution:null,custodyFlows:[{}]}).reason,'ineligible-execution'); assert.equal(l.purchase({execution:{eventId:'x',eligible:true,coverage:COMPLETE},custodyFlows:[{executionId:'other',proven:true}]}).reason,'ambiguous-custody'); assert.equal(l.snapshot().length,0); });
test('unproven marketplace fee ownership cannot create inventory', () => { const l=ledger(); const result=l.purchase({execution:{eventId:'x',eligible:true,coverage:COMPLETE,market:'lm',fees:[{id:'fee',value:c('1'),ownerProven:false}],scope,provenance:'lm',timestamp:'2026-08-01T00:00:00Z',currency:'ATLAS'},custodyFlows:[{executionId:'x',proven:true,lotId:'x',location:'A',asset:'X',quantity:q('1'),payment:c('1')}]}); assert.equal(result.reason,'ambiguous-fee-owner'); assert.equal(l.snapshot().length,0); });
test('unit currency mismatch insufficient quantity and incomplete coverage fail closed', () => { const l=ledger(); assert.throws(()=>l.acquire(event({base:{mining:q('1',0,'USDC')}})),/incompatible-unit/); l.acquire(event({quantity:q('1'),base:{mining:c('1')},coverage:INCOMPLETE})); assert.equal(l.reconcile('UST-1','Carbon').status,INCOMPLETE); assert.throws(()=>l.consume(event({quantity:q('2')})),/insufficient quantity/); });
test('tiny quantities and 128-digit amounts stay exact while order uses time then lot identity', () => { const l=ledger(); l.acquire(event({lotId:'z',timestamp:'2026-08-01T00:00:01Z',asset:'Tiny',quantity:q('1',36),base:{mining:c('1')}})); l.acquire(event({lotId:'a',timestamp:'2026-08-01T00:00:01Z',asset:'Huge',quantity:q('9'.repeat(128)),base:{mining:c('9'.repeat(128))}})); assert.equal(l.reconcile('UST-1','Tiny').quantity.atoms,'1'); assert.equal(l.reconcile('UST-1','Huge').total.atoms,'9'.repeat(128)); });
test('split replay and event ordering remain deterministic', () => { const make=()=>{const l=ledger(); const late=event({eventId:'late',lotId:'b',timestamp:'2026-08-01T00:00:02Z',quantity:q('1'),base:{mining:c('1')}}); const early=event({eventId:'early',lotId:'a',timestamp:'2026-08-01T00:00:01Z',quantity:q('1'),base:{mining:c('1')}}); l.acquire(late);l.acquire(early);return l;}; assert.deepEqual(make().snapshot().map(x=>x.lotId),['a','b']); });

test('attributable costs are replay-safe and failed craft is atomic', () => { const l=ledger(); const lot=l.acquire(event({quantity:q('2'),base:{mining:c('2')}})); const add=event({lotId:lot.lotId,cargo:{fuel:c('1')},coverage:COMPLETE}); l.addAttributableCosts(add); assert.equal(l.addAttributableCosts(add).status,'replay'); const before=l.snapshot(); assert.throws(()=>l.craft(event({outputAsset:'Y',outputQuantity:q('1'),ingredients:[{location:'UST-1',asset:'Carbon',quantity:q('1')},{location:'UST-1',asset:'Missing',quantity:q('1')}],craftingCost:c('1')})),/insufficient quantity/); assert.deepEqual(l.snapshot(),before); });
