'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const bs58Module = require('bs58');
const bs58 = bs58Module.default || bs58Module;
const { preserveTransactionEvidence, scanLocalMarketTrades } = require('../electron/local-market-scanner');
const { adaptExecution, adaptCustodyFlow } = require('../electron/market-event-adapters');
const fs = require('node:fs');
const PROGRAM = 'traderDnaR5w6Tcoi3NFm53i48FTDNbGjBSZwWXDRrg';
const ATLAS = 'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx';
function data(quantity, price) { const d=crypto.createHash('sha256').update('global:process_exchange').digest().subarray(0,8); const a=Buffer.alloc(8),b=Buffer.alloc(8);a.writeBigUInt64LE(BigInt(quantity));b.writeBigUInt64LE(BigInt(price));return bs58.encode(Buffer.concat([d,a,b])); }
function transfer(source,destination,authority,mint,amount,decimals){return{program:'spl-token',parsed:{type:'transferChecked',info:{source,destination,authority,mint,tokenAmount:{amount:String(amount),decimals}}}}}
function rawTx(){return {signature:'sig-raw',slot:9007199254740993n,blockTime:1787443200,meta:{err:null,fee:5000,logMessages:['Program log: Transfer amounts: TransferAmount { purchase_quantity: 2, royalty: 5, transfer_amount: 195, commission: None }'],innerInstructions:[
 {index:0,instructions:[transfer('noise-a','noise-b','noise','OTHER','99',0)]},
 {index:1,instructions:[transfer('buyer-atlas','seller-atlas','buyer',ATLAS,'200',8),transfer('seller-asset','buyer-asset','seller','ASSET','2',0),transfer('buyer-atlas','fee-vault','buyer',ATLAS,'5',8)]},
 {index:2,instructions:[transfer('seller2-asset','buyer2-asset','seller2','ASSET','3',0),transfer('buyer2-atlas','seller2-atlas','buyer2',ATLAS,'300',8)]}
 ],preTokenBalances:[{accountIndex:4,mint:'ASSET',owner:'seller',uiTokenAmount:{amount:'7',decimals:0}},{accountIndex:3,mint:ATLAS,owner:'buyer',uiTokenAmount:{amount:'1000',decimals:8}}],postTokenBalances:[]},transaction:{signatures:['sig-raw'],message:{accountKeys:['payer','buyer','seller',ATLAS,'ASSET','buyer-atlas','seller-atlas','seller-asset','buyer-asset','vault','order-1','buyer2','seller2','buyer2-atlas','seller2-atlas','seller2-asset','buyer2-asset'],instructions:[
 {programId:'other',accounts:[]},
 {programId:PROGRAM,accounts:['buyer','buyer-atlas','buyer-asset',ATLAS,'ASSET','seller','seller-asset','seller-atlas','vault','auth','order-1'],data:data(2,100)},
 {programId:PROGRAM,accounts:['buyer2','buyer2-atlas','buyer2-asset',ATLAS,'ASSET','seller2','seller2-asset','seller2-atlas','vault','auth','order-2'],data:data(3,100)}
 ]}}};}
test('raw immutable coordinates and exact values survive before filtering with deterministic flow links',()=>{const evidence=preserveTransactionEvidence(rawTx(),{market:'LM',trackedWallets:['buyer','buyer2']});assert.equal(evidence.transaction.signature,'sig-raw');assert.equal(evidence.transaction.slot,'9007199254740993');assert.equal(evidence.transaction.transactionFeeLamports,'5000');assert.deepEqual(evidence.executions.map(x=>x.outerInstructionIndex),['1','2']);assert.equal(evidence.executions[0].executionIndex,'1');assert.deepEqual(evidence.executions[0].flowIds,evidence.flows.filter(f=>f.outerInstructionIndex==='1').map(f=>f.flowId));assert.equal(evidence.flows[0].outerInstructionIndex,'0');assert.equal(evidence.flows[0].linkedExecutionIndex,null);assert.equal(evidence.flows.find(f=>f.assetMint==='ASSET'&&f.outerInstructionIndex==='1').assetRawAmount,'2');assert.equal(evidence.executions[0].paymentRawAmount,'200');assert.equal(evidence.executions[0].marketplaceFeeRaw,'5');assert.equal(new Set(evidence.flows.filter(f=>f.linkedExecutionIndex).map(f=>f.flowId)).size,evidence.flows.filter(f=>f.linkedExecutionIndex).length);});
test('B3.2B adapters support complete scanner evidence and keep missing execution coordinates explicit',()=>{const e=preserveTransactionEvidence(rawTx(),{market:'GM',trackedWallets:['buyer','buyer2']});const scope={faction:'USTUR',playerProfile:'buyer'};const execution=adaptExecution(e.executions[0],scope);const flow=adaptCustodyFlow(e.flows.find(f=>f.assetMint==='ASSET'&&f.outerInstructionIndex==='1'),scope);assert.equal(execution.status,'Supported');assert.equal(flow.status,'Supported');const incomplete=preserveTransactionEvidence({...rawTx(),transaction:{...rawTx().transaction,message:{...rawTx().transaction.message,instructions:[]}}},{market:'GM',trackedWallets:['buyer']});assert.equal(incomplete.status,'Incomplete');});
test('coverage reports exhaustion, null transactions and cap without changing RPC counts or legacy arrays',async()=>{let signatureCalls=0,txCalls=0;const connection={async getSignaturesForAddress(){signatureCalls++;return[{signature:'missing',slot:4,blockTime:1787443200,err:null}]},async getParsedTransaction(){txCalls++;return null;}};const result=await scanLocalMarketTrades(connection,{trackedWallets:['wallet'],startIso:'2026-08-22T00:00:00Z',requestsPerSecond:100000,maxPages:1});assert.deepEqual(result.trades,[]);assert.equal(result.stats.totalRpcRequests,2);assert.equal(signatureCalls,1);assert.equal(txCalls,1);assert.equal(result.coverage.status,'Incomplete');assert.equal(result.coverage.missingTransactions,1);assert.equal(result.coverage.pagesRequested,1);assert.equal(result.coverage.signaturesDiscovered,1);assert.equal(result.coverage.transactionsParsed,0);assert.equal(result.coverage.capReached,false);});
test('coverage is complete only on authoritative exhaustion and incomplete on page failure or cap',async()=>{const exhausted=await scanLocalMarketTrades({async getSignaturesForAddress(){return[];}},{trackedWallets:['wallet'],startIso:'2026-08-22T00:00:00Z',requestsPerSecond:100000});assert.equal(exhausted.coverage.status,'Complete');assert.equal(exhausted.coverage.terminationReason,'authoritative_exhaustion');let calls=0;const capped=await scanLocalMarketTrades({async getSignaturesForAddress(){calls++;return Array.from({length:1000},(_,i)=>({signature:`s${calls}-${i}`,slot:i,blockTime:1787443200,err:null}));},async getParsedTransaction(){return null;}},{trackedWallets:['wallet'],startIso:'2026-08-22T00:00:00Z',requestsPerSecond:100000,maxPages:1});assert.equal(capped.coverage.capReached,true);assert.equal(capped.coverage.status,'Incomplete');});

test('staging checkpoints preserve versioned immutable evidence and coverage beside legacy rows',()=>{const main=fs.readFileSync(require.resolve('../electron/main'),'utf8');assert.match(main,/orders: scanned\.orders, trades, immutableEvidence: scanned\.immutableEvidence, coverage: scanned\.coverage/);assert.match(main,/orders: scanned\.orders, trades, assetFlows, immutableEvidence: scanned\.immutableEvidence, coverage: scanned\.coverage/);});
