'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const api=require('../electron/opening-inventory-source-contract');
const at='2026-08-23T00:00:00.000Z',id='snap-1',manifest=['MUD-1\nCarbon','MUD-1\nFuel'];
const rows=[{location:'MUD-1',asset:'Carbon',quantity:'0.000000000000000001',snapshotId:id,snapshotAt:at},{location:'MUD-1',asset:'Fuel',quantity:'0',snapshotId:id,snapshotAt:at}];
const assess=(patch={})=>api.assessSnapshotCycle({rows,expectedIdentities:manifest,snapshotId:id,snapshotAt:at,complete:true,expectedRowCount:2,...patch});
test('complete full snapshot preserves raw tiny decimal and explicit zero',()=>{const x=assess();assert.equal(x.status,'complete');assert.equal(x.rows[0].quantity,'0.000000000000000001');assert.equal(x.rows[1].quantity,'0')});
test('sparse or partial snapshot is unavailable',()=>assert.equal(assess({rows:rows.slice(0,1)}).reason,'partial-snapshot'));
test('missing identity is distinct from unknown identity',()=>{assert.equal(assess({rows:rows.slice(0,1)}).reason,'partial-snapshot');assert.equal(assess({rows:[...rows,{location:'MUD-1',asset:'Unknown',quantity:'1',snapshotId:id,snapshotAt:at}]}).reason,'unknown-identity')});
test('duplicate rows are unavailable',()=>assert.equal(assess({rows:[...rows,rows[0]]}).reason,'duplicate-identity'));
test('late correction with different snapshot identity cannot mix cycles',()=>assert.equal(assess({rows:[rows[0],{...rows[1],snapshotId:'correction'}]}).reason,'mixed-cycle'));
test('missing completion metadata cannot claim a snapshot',()=>assert.equal(assess({complete:false}).reason,'missing-cycle-proof'));
test('mutable daily aggregate is not immutable event evidence',()=>assert.equal(api.assessForwardEvent({identity:'day:MUD:2026-08-23',timestamp:at,mutableDailyAggregate:true}).reason,'mutable-daily-aggregate'));
test('immutable replay excludes before T and includes exactly/after T',()=>{const events=[{identity:'tx:a',timestamp:'2026-08-22T23:59:59.999Z'},{identity:'tx:b',timestamp:at},{identity:'tx:c',timestamp:'2026-08-23T00:00:00.001Z'}];assert.deepEqual(api.boundaryReplay(events,at).map(x=>x.identity),['tx:b','tx:c'])});
