'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs/promises'); const os=require('node:os'); const path=require('node:path');
const api=require('../electron/opening-inventory-checkpoint');
const scope={faction:'USTUR',playerProfile:'Profile111',sourceTimestamp:'2026-08-22T12:00:00.000Z',rows:[{location:'UST Starbase 1',asset:'Iron Ore',quantity:'10.000000000000000001'}]};
async function root(){return fs.mkdtemp(path.join(os.tmpdir(),'msa-opening-'));} async function raw(root,f='USTUR',p='Profile111'){return fs.readFile(api.pathsFor(root,f,p).document,'utf8');}
test('first creation, deterministic hash, and round-trip preserve tiny decimal as uncosted Incomplete',async()=>{const r=await root();const a=await api.saveOpeningInventoryCheckpoint({root:r,...scope},{now:'2026-08-22T12:01:00.000Z'});assert.equal(a.status,'created');assert.equal(a.document.rows[0].quantity,'10.000000000000000001');assert.equal(a.document.rows[0].costCoverage,'uncosted');assert.equal(a.document.rows[0].status,'Incomplete');assert.equal(a.document.eventBoundaryTimestamp,scope.sourceTimestamp);const b=await api.loadOpeningInventoryCheckpoint({root:r,faction:scope.faction,playerProfile:scope.playerProfile});assert.equal(b.status,'loaded');assert.equal(b.document.contentHash,a.document.contentHash);const c=await api.saveOpeningInventoryCheckpoint({root:r,...scope},{now:'2026-08-22T13:00:00.000Z'});assert.equal(c.status,'loaded');assert.equal(c.written,false);assert.equal(c.document.createdAt,a.document.createdAt)});
test('faction and player identity isolate storage and reject mismatched document scope',async()=>{const r=await root();await api.saveOpeningInventoryCheckpoint({root:r,...scope},{now:'2026-08-22T12:01:00.000Z'});assert.equal((await api.loadOpeningInventoryCheckpoint({root:r,faction:'MUD',playerProfile:scope.playerProfile})).status,'missing');assert.equal((await api.loadOpeningInventoryCheckpoint({root:r,faction:'USTUR',playerProfile:'Other111'})).status,'missing');const p=api.pathsFor(r,'USTUR','Other111');await fs.mkdir(p.directory,{recursive:true});await fs.writeFile(p.document,await raw(r));assert.equal((await api.loadOpeningInventoryCheckpoint({root:r,faction:'USTUR',playerProfile:'Other111'})).status,'scope-mismatch')});
test('wrong schema and corrupt JSON are invalid and preserved',async()=>{for(const text of ['{"schemaVersion":2}','{bad']){const r=await root(),p=api.pathsFor(r,scope.faction,scope.playerProfile);await fs.mkdir(p.directory,{recursive:true});await fs.writeFile(p.document,text);assert.equal((await api.loadOpeningInventoryCheckpoint({root:r,faction:scope.faction,playerProfile:scope.playerProfile})).status,'invalid');assert.equal(await fs.readFile(p.document,'utf8'),text);assert.equal((await api.saveOpeningInventoryCheckpoint({root:r,...scope},{now:'2026-08-22T12:01:00.000Z'})).status,'invalid');assert.equal(await fs.readFile(p.document,'utf8'),text)}});
test('invalid, negative, missing, non-finite, numeric, and zero quantities fail closed',async()=>{for(const quantity of [undefined,'-1','NaN','Infinity',1,'0','0.0','1e-9']){const r=await root();const out=await api.saveOpeningInventoryCheckpoint({root:r,...scope,rows:[{location:'UST-1',asset:'Carbon',quantity}]},{now:'2026-08-22T12:01:00.000Z'});assert.equal(out.status,'invalid',String(quantity))}});
test('duplicate location and asset identity is rejected',async()=>{const r=await root();const out=await api.saveOpeningInventoryCheckpoint({root:r,...scope,rows:[scope.rows[0],scope.rows[0]]},{now:'2026-08-22T12:01:00.000Z'});assert.equal(out.status,'invalid');assert.match(out.error,/duplicate/)});
test('atomic failure leaves previous valid checkpoint recoverable',async()=>{const r=await root();await api.saveOpeningInventoryCheckpoint({root:r,...scope},{now:'2026-08-22T12:01:00.000Z'});const before=await raw(r);const out=await api.saveOpeningInventoryCheckpoint({root:r,...scope,sourceTimestamp:'2026-08-23T12:00:00.000Z'},{now:'2026-08-23T12:01:00.000Z',writeHooks:{beforeRename(){throw new Error('injected')}}});assert.equal(out.status,'save-failed');assert.equal(await raw(r),before);assert.equal((await api.loadOpeningInventoryCheckpoint({root:r,faction:scope.faction,playerProfile:scope.playerProfile})).status,'loaded')});
test('concurrent creation serializes and leaves one valid complete snapshot',async()=>{const r=await root();const [a,b]=await Promise.all([api.saveOpeningInventoryCheckpoint({root:r,...scope},{now:'2026-08-22T12:01:00.000Z'}),api.saveOpeningInventoryCheckpoint({root:r,...scope},{now:'2026-08-22T12:01:00.000Z'})]);assert.deepEqual([a.status,b.status].sort(),['created','loaded']);assert.equal((await api.loadOpeningInventoryCheckpoint({root:r,faction:scope.faction,playerProfile:scope.playerProfile})).status,'loaded')});
test('document contains no credentials, endpoint, price, or fabricated basis fields',async()=>{const r=await root();await api.saveOpeningInventoryCheckpoint({root:r,...scope,token:'secret',rpcUrl:'https://secret',currentPrice:99},{now:'2026-08-22T12:01:00.000Z'});const text=await raw(r);for(const forbidden of ['secret','https://','token','rpcUrl','currentPrice','price','totalCost'])assert.doesNotMatch(text,new RegExp(forbidden,'i'))});
